doNaturalEliteMobSpawning: true
doSpawnersSpawnEliteMobs: false
eliteMobsSpawnPercentage: 0.05
superMobStackRange: 15
naturalEliteMobsLevelCap: 250
doElitesWearArmor: true
doElitesWearHelmets: true
doNaturalEliteMobVisualEffects: true
doSpawnerEliteMobVisualEffects: false
doPowerBuildupVisualEffects: true
doCustomEliteMobsDeathMessages: true
doDisplayMobHealthOnHit: true
doDisplayMobDamageOnHit: true
doIncreaseEliteMobLevelBasedOnSpawnDistance: false
distanceBetweenIncrements: 100.0
levelIncreaseAtIncrements: 1.0
hideEliteMobPowersUntilAggro: true
damageToEliteMobMultiplier: 1.0
damageToPlayerMultiplier: 1.0
showCustomBossLocation: true
bossLocationMessage: '&7[EM] &2[点击追踪]'
commandsOnEliteMobDeath: [ ]
bossKillParticipationMessage: '&e你造成的伤害：&2$playerDamage'
regenerateCustomBossHealthOnCombatEnd: true
defaultOtherWorldBossLocationMessage: '$name：在不同的世界！'
